### ISSUE TITLE
SDK print success or failure of Test in output.log.

### ISSUE THREAD

**Issue by deekoder** [minio/mint#103]
Only print TestName Success/Failure in output.log
Only print same TestName and failure error message in error.log. Otherwise retrospecting is quite impossible on why a test failed.

**Comment by deekoder** [comment]
Ruby is a nice example of how each test case should log for retrospective analysis.

**Comment by NitishT** [comment]
Closing this as this will be fixed by the new mint log format 

- https://github.com/minio/minio-dotnet/issues/160
- https://github.com/minio/minio-go/issues/779
- https://github.com/minio/minio-py/issues/565
- https://github.com/minio/minio-js/issues/614
- https://github.com/minio/minio-java/issues/597
- #114 
- #111 
- #112 
- #113
