### ISSUE TITLE
Gateway: Awscli head-object test fails 

### ISSUE THREAD

**Issue by kannappanr** [minio/mint#231]
Awscli headobject test fails on all gateways.
Here is the failure entry

```

{"name": "awscli", "duration": 7574, "function": "aws --endpoint-url http://192.168.86.102:9000 s3api head-object --bucket awscli-mint-test-bucket-11375 --key prefix/directory/\n", "status": "FAIL", "error": "An error occurred (404) when calling the HeadObject operation: Not Found"}

```
This call succeeds on regular server mode.

**Comment by harshavardhana** [comment]
Ah this would be expected :( since the special behavior is only for minio server mode. We  can either fix the gateway to create a prefix like doing a PUT with "/" object and then create an object. This is an overkill on the namespace of the backend and we don't need to do that. 

Perhaps we can remove this test or either way a mint mode to test only server functionality??

**Comment by harshavardhana** [comment]
Actually the test is wrong it should create the directory first and expect the compatible behavior.

**Comment by nitisht** [comment]
assigning to @harshavardhana as discussed.
